kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && sleep 100000000 || exit 1"
    volumeMounts:
      - name: nexenta-stor-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nexenta-stor-pvc
      persistentVolumeClaim:
        claimName: nexenta-stor
