apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
  - name: nfs-test
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/mount"
      name: nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
